services:
  - title: "The 39th, 40th Annual AAAI Conference on Artificial Intelligence (AAAI 2025, 2026)"
    role: PC Member
    conference: y

  - title: "The 38th, 39th, 40th Annual AAAI Conference on Artificial Intelligence for Social Impact (AISI 2024, 2025, 2026)"
    role: PC Member
    conference: y

  - title: "The 29th, 30th International Conference on Database Systems for Advanced Applications (DASFAA 2024, 2025)"
    role: PC Member
    conference: y

  - title: "The 8th IEEE Conference on Energy Internet and Energy System Integration (EI2 2024)"
    role: PC Member
    conference: y

  - title: "The 12th International Conference on Behavioural and Social Computing (BESC 2025)"
    role: PC Member
    conference: y
  
  - title: "The 2023 Conference on Empirical Methods in Natural Language Processing (EMNLP 2023)"
    role: Reviewer
    conference: y

  - title: "The 32nd International Joint Conference on Artificial Intelligence (IJCAI 2023)"
    role: Reviewer
    conference: y
  
  - title: "The 2023 ACM SIGKDD International Conference on Knowledge Discovery and Data Mining (KDD 2023)"
    role: Reviewer
    conference: y

  - title: "Sustainability: Special Issue \"Renewable and Sustainable Energy Systems: Architecture, Methodology and Technology, 2nd Edition\""
    role: Leading Guest Editor
    journal: y
  
  - title: "Information Fusion 2025"
    role: Reviewer
    journal: y
  
  - title: "Transactions on Consumer Electronics 2025"
    role: Reviewer
    journal: y
  
  - title: "Journal of Advances in Information Technology 2025"
    role: Reviewer
    journal: y

  - title: "Transactions on Knowledge Discovery from Data 2024"
    role: Reviewer
    journal: y
    
  - title: "IEEE Transactions on Knowledge and Data Engineering 2023"
    role: Reviewer
    journal: y
